### ISSUE TITLE
update cheeatsheets

### ISSUE THREAD

**Issue by perfecto25** [hbokh/awesome-saltstack#18]
Hi, one of the cheatsheet links "bladelogic", thats my very old salt cheatsheet, 

the newest and updated one is here, with way more stuff,

https://sites.google.com/site/mrxpalmeiras/saltstack/salt-cheat-sheet

**Comment by hbokh** [comment]
Thanks! Fixed.

**Comment by hbokh** [comment]
Thanks! Fixed.
