### ISSUE TITLE
Modules and integrations

### ISSUE THREAD

**Issue by amendlik** [hbokh/awesome-saltstack#29]
Here two suggestions for additional content, and some examples:

1. Modules - community developed plugins that are not part of the Salt repository
 - https://github.com/saltstack/salt-contrib
 - https://github.com/amendlik/gitstack-pillar

2. Integrations - code/tools that make Salt work with other products
 - https://plugins.jenkins.io/saltstack/
 - https://github.com/amendlik/salt-gen-resource
 - https://github.com/rundeck-plugins/salt-step

**Comment by hbokh** [comment]
Thanks!
I've integrated some of your suggestions. Also added a new section "Integrations".
